# Analitik dan Visualisasi Data: Pra Pemrosesan Data

## 1. Pembersihan Data

In [9]:
import pandas as pd
data_path = 'G:\.shortcut-targets-by-id\\1tw6CsgTzgMxIYBkoFdTr5yZKeJq1729j\KULIAH\\00 - UNEJ\PEMROGRAMAN\My Program\Python\Python JNotebook\Analitik Dan Visualisasi Data\Pertemuan 9 - Pra-pemrosesan Data\\nba.csv'
nba = pd.read_csv(data_path)
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 1.1 Menangani Nilai yang Kosong

In [ ]:
'''
any = salah satu kolom kosong maka dianggap kosong
all = salah satu kolom kosong tidak dianggap kosong, untuk dianggap kosong maka seluruh kolom harus kosong

axis:
 - 1: data akan dicek secara horizontal atau per baris
 - 0: data akan dicek secara vertical atau per kolom

 misalkan:
 - any dan axisnya adalah 1 maka data akan dicek apakah pada setiap baris terdapat salah satu kolom yang kosong, jik
   iya maka data akan ditandai kosong 
'''

is_na = nba.isna().all(axis=1)
is_na

nba.loc[is_na]

#### 1.1.1 Menghapus Nilai Kosong

##### 1.1.1.1 Menghapus Nilai Kosong Menggunakan Any dan Secara Horizontal

In [10]:
nba_any = nba.dropna(axis=0, how='any')
nba_any.shape[0]

364

##### 1.1.1.2 Menghapus Nilai Kosong Menggunakan All dan Secara Horizontal

In [11]:
nba_any = nba.dropna(axis=0, how='all')
nba_any

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

##### 1.1.1.3 Menghapus Nilai Kosong Menggunakan Any dan Secara Vertical

In [ ]:
nba_any = nba.dropna(axis=1, how='any')
# nba_any.shape[1]
nba_any

##### 1.1.1.4 Menghapus Nilai Kosong Menggunakan All dan Secara Vertical

In [ ]:
nba_any = nba.dropna(axis=1, how='all')
nba_any.shape[0]

#### 1.1.2 Mengisi Nilai

##### 1.1.2.1 Mengisi dengan Nilai yang Ditentukan

In [ ]:
nba.loc[:,'Number'].fillna(10)

In [ ]:
nba.loc[is_na, 'Number']

##### 1.1.2.2 Mengisi dengan Nilai Setelahnya

In [ ]:
print(nba)
is_na = nba[nba.isnull().any(axis=1)].index
# print(nba.iloc[is_na])
replaced_nba = nba.fillna(method='bfill')
print(replaced_nba.iloc[is_na])

##### 1.1.2.2 Mengisi dengan Nilai Sebelumnya

In [ ]:
print(nba)
is_na = nba[nba.isnull().any(axis=1)].index
replaced_nba = nba.fillna(method='pad')
print(replaced_nba.iloc[is_na])

##### 1.1.2.3 Mengisi dengan Interpolasi

In [ ]:
nba.interpolate(method='linear')

### 1.2 Menghapus Data yang Duplikat

In [ ]:
# menduplikasi data
duplicated = nba.append(nba.iloc[[-2]], ignore_index=True)
duplicated

In [ ]:
duplicated_nba = duplicated.duplicated()
duplicated_nba[duplicated_nba==True].index

In [ ]:
duplicated.drop(duplicated[duplicated_nba].index)

In [ ]:
nba_duplicated_free = nba.drop_duplicates()
nba_duplicated_free.groupby(['Team'])['Team'].count()

### 1.3 Standarisasi Data

In [ ]:
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',',names=['sepal_length','sepal_width','petal_length','petal_width','class'])
iris

In [ ]:
code = 1
for i in iris.loc[:,'class'].unique():
  iris['class'].loc[iris['class']==i] = code
  code += 1
iris

In [ ]:
iris['class'] = iris['class'].astype('int64')
iris

In [ ]:
from sklearn.preprocessing import StandardScaler

iris_standarded = StandardScaler().fit_transform(iris.iloc[:,:4])
iris_standarded = pd.DataFrame(iris_standarded)
iris_standarded = pd.concat([iris_standarded, iris['class']], ignore_index=True, axis=1)
iris_standarded.columns = iris.columns
iris_standarded

### 1.3 Reduksi Data

#### 1.3.1 Uji Korelasi antar Fitur

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
iris_corr = iris_standarded.corr()
plt.figure(figsize=(12,10))
sns.heatmap(iris_corr, annot=True, cmap=plt.cm.Reds)
plt.show()

In [ ]:
iris_class_corr = abs(iris_corr['class'].drop(['class']))
iris_class_corr>0.5

In [ ]:
iris_class_corr_index = iris_class_corr[iris_class_corr>0.5].index
iris_reduction = iris_standarded[iris_class_corr_index]
iris_reduction['class'] = iris['class']
iris_reduction

### 1.4 Mengidentifikasi atau Menghapus Outlier

$IQR = Q3-Q1$

$Upper Bound = Q3 + 1.5 * IQR $

$Lower Bound = Q1 - 1.5 * IQR$

In [ ]:
quantile = iris_reduction.quantile([0.25, 0.75])
quantile = quantile.drop('class', axis=1)
quantile

In [ ]:
iqr = quantile.iloc[1]-quantile.iloc[0]
iqr

In [ ]:
quantile.loc[0.25] = quantile.loc[0.25]-iqr*1.5
quantile.loc[0.75] = quantile.loc[0.75]+iqr*1.5

# for col in iqr.index:
#   print(iris_redcution[iris_reduction[col]<quantile.loc[0.25,col] & iris_redcution[col]>quantile.loc[0.75,col]])
#   break

lower = iris_reduction['sepal_length']>=quantile.loc[0.25,'sepal_length']
upper = iris_reduction['sepal_length']<=quantile.loc[0.75,'sepal_length']
iris_reduction[(lower & upper)]

### 1.5 Mengatasi Inkonsistensi

## 2. Integrasi Data

## 3. Transformasi Data

## 4. Reduksi Data

## 5. Diskritisasi Data